Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,12 +37,12 @@ jobs:
 #         with:
 #           ssh-private-key: ${{ secrets.PRIVATE_KEY }}
         
-#       - name: id rsa
-#         env:
-#           TOKEN: ${{ secrets.PRIVATE_KEY }}
-#         run: |
-#           install -m 600 -D /dev/null ~/.ssh/id_rsa
-#           echo "$TOKEN" > ~/.ssh/id_rsa
+      - name: id rsa
+        env:
+          TOKEN: ${{ secrets.PRIVATE_KEY }}
+        run: |
+          install -m 600 -D /dev/null ~/.ssh/id_rsa
+          echo "$TOKEN" > ~/.ssh/id_rsa
 
         
 #       - name: test1
@@ -56,22 +56,22 @@ jobs:
         
         
         
-      - name: Test1
-        run: |
-          for i in {0..60}; do
-            sleep 10
-            response=$(curl -s http://134.209.152.184/v2/info)
-            if [ $? -eq 0 ] && [ "$(jq -e 'has("data")' <<< "$response")" == "true" ]; then
-              echo "$response" > response_v2.json
-              last_block_timestamp=$(jq -r '.data.lastBlock.timestamp' response_v2.json)
-              current_timestamp=$(date +%s)
-              if [[ "$last_block_timestamp" -gt $((current_timestamp - 300)) ]]; then
-                break
-              fi
-            else
-              echo "Failed to get JSON response, continuing the loop..."
-            fi
-          done
+#       - name: Test1
+#         run: |
+#           for i in {0..60}; do
+#             sleep 10
+#             response=$(curl -s http://134.209.152.184/v2/info)
+#             if [ $? -eq 0 ] && [ "$(jq -e 'has("data")' <<< "$response")" == "true" ]; then
+#               echo "$response" > response_v2.json
+#               last_block_timestamp=$(jq -r '.data.lastBlock.timestamp' response_v2.json)
+#               current_timestamp=$(date +%s)
+#               if [[ "$last_block_timestamp" -gt $((current_timestamp - 300)) ]]; then
+#                 break
+#               fi
+#             else
+#               echo "Failed to get JSON response, continuing the loop..."
+#             fi
+#           done
            
 #       - name: test2
 #         run: |
@@ -112,10 +112,10 @@ jobs:
 #       - name: env
 #         run: env
 
-#       - name: Install requirements
-#         run: |
-#           pip install ansible
-#           sudo apt-get install -y python3-netaddr 
+      - name: Install requirements
+        run: |
+          pip install ansible
+          sudo apt-get install -y python3-netaddr 
 
 #       - name: Generate SSH key pair
 #         id: generate_ssh_key
@@ -127,54 +127,54 @@ jobs:
 # #         run: |
 # #          echo ${{ secrets.HUI }} > do.yml
 
-#       - name: Intall doctl
-#         uses: digitalocean/action-doctl@v2
-#         with:
-#             token: ${{ secrets.DIGITALOCEAN_TOKEN }}
+      - name: Intall doctl
+        uses: digitalocean/action-doctl@v2
+        with:
+            token: ${{ secrets.DIGITALOCEAN_TOKEN }}
 
-#       - name: test
-#         run: doctl projects list
+      - name: test
+        run: doctl projects list
         
-#       - name: test
-#         run: doctl projects update beab609f-428f-42ce-b5a6-fadfa9d9d7cf --is_default=true
+      - name: test
+        run: doctl projects update beab609f-428f-42ce-b5a6-fadfa9d9d7cf --is_default=true
 
-#       - name: Create SSH key in DigitalOcean
-#         id: create_ssh_key
-#         run: |
-#          random_name=$(openssl rand -hex 4)
-#          echo "::set-output name=ssh::$(doctl compute ssh-key create ${random_name}-ssh-key --public-key "${{ steps.generate_ssh_key.outputs.public_key }}" --format ID --no-header)"
+      - name: Create SSH key in DigitalOcean
+        id: create_ssh_key
+        run: |
+         random_name=$(openssl rand -hex 4)
+         echo "::set-output name=ssh::$(doctl compute ssh-key create ${random_name}-ssh-key --public-key "${{ secrets.PRIVATE_KEY }}" --format ID --no-header)"
            
-#       - name: Create Droplet
-#         run: doctl compute droplet create deploy-test --image debian-10-x64 --region nyc1 --size s-1vcpu-2gb --ssh-keys "${{ steps.create_ssh_key.outputs.ssh }}"
+      - name: Create Droplet
+        run: doctl compute droplet create deploy-test --image debian-10-x64 --region nyc1 --size s-1vcpu-2gb --ssh-keys "${{ steps.create_ssh_key.outputs.ssh }}"
 
-#       - name: Wait create Droplet
-#         run: sleep 40s
+      - name: Wait create Droplet
+        run: sleep 40s
         
-#       - name: Get Droplet IP
-#         id: droplet
-#         run: |
-#          echo "::set-output name=ip::$(doctl compute droplet list deploy-test --format PublicIPv4 --no-header)"
-#          echo "::set-output name=id::$(doctl compute droplet list deploy-test --format ID --no-header)"
+      - name: Get Droplet IP
+        id: droplet
+        run: |
+         echo "::set-output name=ip::$(doctl compute droplet list deploy-test --format PublicIPv4 --no-header)"
+         echo "::set-output name=id::$(doctl compute droplet list deploy-test --format ID --no-header)"
 
-#       - name: Create Volume
-#         id: volume
-#         run:  echo "::set-output name=volume::$(doctl compute volume create backup-storage --region nyc1 --size 100GB --format ID --no-header)"
+      - name: Create Volume
+        id: volume
+        run:  echo "::set-output name=volume::$(doctl compute volume create backup-storage --region nyc1 --size 100GB --format ID --no-header)"
 
-#       - name: attach volume
-#         run: doctl compute volume-action attach "${{ steps.volume.outputs.volume }}" "${{ steps.droplet.outputs.id  }}"
+      - name: attach volume
+        run: doctl compute volume-action attach "${{ steps.volume.outputs.volume }}" "${{ steps.droplet.outputs.id  }}"
 
-#       - name: Setup Ansible Inventory
-#         run: echo "$INVENTORY_CONTENTS" > inventory.ini
-#         env:
-#           INVENTORY_CONTENTS: |
-#             [web]
-#             qwerty ansible_host=${{ steps.droplet.outputs.ip }}
+      - name: Setup Ansible Inventory
+        run: echo "$INVENTORY_CONTENTS" > inventory.ini
+        env:
+          INVENTORY_CONTENTS: |
+            [web]
+            qwerty ansible_host=${{ steps.droplet.outputs.ip }}
             
 #       - name: Status volume
 #         run: doctl compute droplet list deploy-test
         
-#       - name: Test
-#         run: ansible-playbook -i inventory.ini test.yml -e "extra_host=qwerty" --user root --key-file "~/.ssh/id_rsa"
+      - name: Test
+        run: ansible-playbook -i inventory.ini test.yml -e "extra_host=qwerty" --user root --key-file "~/.ssh/id_rsa"
 
       # - name: Deploy common.yml
       #   run: ansible-playbook -i env/prod ansible/common.yml
@@ -208,18 +208,18 @@ jobs:
       # - name: Backup explorer
       #   run: ansible-playbook -i env/prod ansible/explorer_v2_backup.yml
 
-#       - name: Rm ssh keys
-#         if: always()
-#         run: doctl compute ssh-key delete "${{ steps.create_ssh_key.outputs.ssh }}" --force
+      - name: Rm ssh keys
+        if: always()
+        run: doctl compute ssh-key delete "${{ steps.create_ssh_key.outputs.ssh }}" --force
         
-#       - name: Destroy Droplet
-#         if: always()
-#         run: |
-#          doctl compute volume-action detach "${{ steps.volume.outputs.volume }}" "${{ steps.droplet.outputs.id }}"
-#          doctl compute droplet delete deploy-test --force
+      - name: Destroy Droplet
+        if: always()
+        run: |
+         doctl compute volume-action detach "${{ steps.volume.outputs.volume }}" "${{ steps.droplet.outputs.id }}"
+         doctl compute droplet delete deploy-test --force
         
-#       - name: Detach and rm volume 
-#         if: always()
-#         run: |
-#          doctl compute volume delete "${{ steps.volume.outputs.volume }}" --force       
+      - name: Detach and rm volume 
+        if: always()
+        run: |
+         doctl compute volume delete "${{ steps.volume.outputs.volume }}" --force       
 
